### ISSUE TITLE
Wuzz can't handle responses other than JSON?

### ISSUE THREAD

**Issue by tobiasboyd** [asciimoo/wuzz#20]
Trying it against an API that returns XML, no results are displayed, only the headers. It seems like at a minimum it would be friendly to show an error/warning that wuzz can't parse the body of the response... and maybe indicate in the readme what it can handle?

**Comment by asciimoo** [comment]
@tobiasboyd, empty response body is strange.. wuzz should display all text based responses - it works for me with XML. Could you provide an URL where I can reproduce the error?

**Comment by karlbateman** [comment]
Wuzz dies when accessing `brotli` encoded data i.e.

```bash
wuzz http://httpbin.org/brotli
```

Gives me the following error
```bash
panic: json formatter error

goroutine 1 [running]:
log.Panicln(0xc42004de80, 0x1, 0x1)
	/usr/local/go/src/log/log.go:336 +0xc0
main.main()
	/Users/karlbateman/go/src/github.com/asciimoo/wuzz/wuzz.go:1743 +0xb35
```

**Comment by asciimoo** [comment]
@karlbateman, the standard http lib in go can't decode brotli compressed responses.
I added a more graceful error handling in 07ede4e .

**Comment by karlbateman** [comment]
@asciimoo Handling that gracefully is great 👍
