### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cctse** [asciimoo/wuzz#86]
on mac mini

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12e9b1a]

goroutine 1 [running]:
main.(*StatusLine).Update(0x0, 0xc42011a690, 0xc420016460)
	/Users/akc/go/src/github.com/asciimoo/wuzz/status-line.go:31 +0x6a
main.(*App).Layout(0xc420016460, 0xc4200f2090, 0xc4200d68e0, 0xc420049aa0)
	/Users/akc/go/src/github.com/asciimoo/wuzz/wuzz.go:589 +0x3c9
main.(*App).ParseArgs(0xc420016460, 0xc4200f2090, 0xc420010220, 0x1, 0x1, 0x1f, 0x0)
	/Users/akc/go/src/github.com/asciimoo/wuzz/wuzz.go:1301 +0x50
main.main()
	/Users/akc/go/src/github.com/asciimoo/wuzz/wuzz.go:1616 +0x94f
ak:~ akc$
```

**Comment by cryptobird** [comment]
Bump; I got this same error on my macbook pro

**Comment by Benaiah** [comment]
Is this happening on startup or is something else triggering it?

**Comment by cctse** [comment]
thanks
